### ISSUE TITLE
Wrong winner detected

### ISSUE THREAD

**Issue by kungfoolfighting** [scopatz/w3g#11]
Hello,

I am having an issue with the winner detection. Lady Risa replay tool detects the correct winner, but this lib detects the wrong winner. This is the example replay: 
[replay](https://creepcamp.de/media/replays/RBTV%20Liga%20Season%207/Liga%201/Paxa.United_vs_TapioN_Last_Refuge.w3g)
Winner should be player Tapion, but at least in my tests the lib detects the wrong winner.

Is this something that could be fixed anytime soon?

**Comment by scopatz** [comment]
I'll try to find some time to take a look, but it would be helpful if we knew what the underlying issue is.

**Comment by SantoDE** [comment]
Hey @scopatz,

I tried to figure it out as well. It looks strange to me. It looks like, as if there is no proper leave event and thus, the lib considers the wrong player as a winner. But im unsure. Maybe we can pair on that?

**Comment by scopatz** [comment]
Yeah, I think that is true, IIRC. PRs very welcome here

**Comment by SantoDE** [comment]
Cool! Any hints on how to tackle it?

**Comment by SantoDE** [comment]
Update: I digged a lot deeper and figured, that "result()" is incorrectly reporting "lost" for the player who won. But from here, its very tight to the actual w3g format where im not that confident in...

**Edit** @scopatz if you have any ideas based on my recent findings, just shoot (= You probably know more than I do!
