### ISSUE TITLE
Error when opening replay

### ISSUE THREAD

**Issue by hhllcks** [scopatz/w3g#2]
Hi, I was trying to open a fresh (1.29) ladder game and it does not work.

Tried it with python 2.7 and python 3.

`$ python w3g.py rep.w3g
Traceback (most recent call last):
  File "w3g.py", line 1424, in <module>
    main()
  File "w3g.py", line 1414, in main
    f = File(sys.argv[1])
  File "w3g.py", line 1036, in __init__
    self._read_blocks()
  File "w3g.py", line 1107, in _read_blocks
    self._parse_blocks(data)
  File "w3g.py", line 1125, in _parse_blocks
    offset = self._parse_startup(data)
  File "w3g.py", line 1191, in _parse_startup
    self.select_mode = SELECT_MODES[b2i(data[offset])]
KeyError: 172`

[rep.w3g.zip](https://github.com/scopatz/w3g/files/1968742/rep.w3g.zip)

**Comment by hhllcks** [comment]
I added the value 0xac (172) to the dictionary SELECT_MODES like this:

`SELECT_MODES = {
    0x00: 'team & race selectable',
    0x01: 'team not selectable',
    0x03: 'team & race not selectable',
    0x04: 'race fixed to random',
    0xac: 'automated match making',
    0xcc: 'automated match making',
    }`

Now everything seems fine and the parser works as intended. Maybe Blizzard changed something with Patch 1.29?

**Comment by scopatz** [comment]
Hi @hhllcks! Thanks for bringing this up.  I am sure that this is because of the 1.29 patch.  Would you mind putting in PR with your fix?
