### ISSUE TITLE
Any practical use?

### ISSUE THREAD

**Issue by BarbzYHOOL** [scopatz/w3g#4]
Just being curious

You say it can be used to make stats. but is that all?

**Comment by scopatz** [comment]
What do you mean by practical here?

**Comment by BarbzYHOOL** [comment]
Just wondering what can be the use since I know a bit of python and used to play wc3 and watch some replays

**Comment by scopatz** [comment]
Well, it is mostly useful for analysis of games and players.  Unfortunately, you can't replay the games themselves without the War 3 client.

**Comment by BarbzYHOOL** [comment]
ty
